apiVersion: skaffold/v1
kind: Config
metadata:
  name: billing-app
build:
  artifacts:
  - image: 984283681696.dkr.ecr.us-east-1.amazonaws.com/billing
    jib:
      project: backend
deploy:
#  kubectl:
#    manifests:
#    - _K8S/k8s-app.yaml
  helm:
    releases:
      - name: "{{.HELM_RELEASE_NAME_ENV}}"
        chartPath: billing-app
        recreatePods: true
        values:
          image.repository: 984283681696.dkr.ecr.us-east-1.amazonaws.com/billing
        setValueTemplates:
          namespace: "{{.HELM_NAMESPACE_ENV}}"
    flags:
      global: ["--atomic"]
