apiVersion: v1
kind: Namespace
metadata:
  name: billing-application
---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: billing-app-deployment
  namespace: billing-application
  labels:
    app: billing-app-deployment
    tier: backend
spec:
  selector:
    matchLabels:
      app: billing-app-deployment
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: billing-app-deployment
        tier: backend
    spec:
      containers:
        - name: billing-app
          image: '984283681696.dkr.ecr.us-east-1.amazonaws.com/billing:latest'
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: billing-backend
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: billing-app-service
  namespace: billing-application
  labels:
    app: billing-app-service
    tier: backend
spec:
  type: LoadBalancer
  ports:
    - name: billing-backend
      port: 8080
      targetPort: 8080
  selector:
    app: billing-app-deployment
